package project.tms.daoLayer.entityLayer.Train;

public interface ExercisesName {
    String SHRUGS = "shrugs"; //шраги
    String FACE_PULLS = "facePulls"; //горизонтальная тяга к лицу
    String UPRIGHT_ROWS = "uprightRows"; //тяга к подбородку
    String STANDING_DUMBBELL_PRESS = "standingDumbbellPress"; //жим вверх
    String Prone_Reverse_Fly = "proneReverseFFly";// лежа на скамье разводка на задние дельты
    String Lateral_Raises = "lateralRaises";//разводка в стороны на дельты
    String LIFTING_DUMBBELLS_IN_FRONT_OF_YOU = "liftingDumbbellsInFrontOfYou";//подьемы перед собой
    String BARBELL_CURL = "barbellCurl";// штанга на бицепс
    String DUMBBELL_CURL = "dumbbellCurl";// гантели на бицепс
    String CHIN_UP = "chinUp";// подтягивания обратным хватом
    String HAMMER_CURL = "hammerCurl";// молот на бицепс
    String SKULLCRUSHER = "skullcrusher";// франц жим
    String CLOSE_GRIP_BENCH_PRESS = "closeGripBenchPress";// жим узким хватом
    String BENCH_DIP = "benchDip";// трицепс от скамьи
    String CABLE_PUSH_DOWN = "cablePushDown";// трицепс жим палки вниз
    String PLATE_PINCH = "platePinch";// удержание дисков пальцами
    String PULL_UP = "pullUp";// подтягивания
    String LAT_PULLDOWN = "latPulldown";// тяга вертикального блока
    String CABLE_ROW = "cableRow";// тяга горизонтального блока
    String BACK_EXTENSION = "backExtension";// гиперэкстензия
    String DEADLIFT = "deadlift";// мертвая тяга
    String BENT_OVER_ROW = "bentOverRow";// тяга в наклоне
    String BARBELL_BENCH_PRESS = "barbellBenchPress";// жим лежа
    String DUMBBELL_BENCH_PRESS = "dumbbellBenchPress";// жим лежа с гантелями
    String CHEST_PRESS_MACHINE = "chestPressMachine";// бабочка
    String LOW_CABLE_CROSSOVER = "lowCableCrossover";// жим в кроссовере на низ груди
    String WIDE_GRIP_DIPS = "wideGripDips";// брусья
    String PLANK = "plank";// планка
    String REVERSE_CRUNCH = "reverseCrunch";// скручивание ног к телу
    String CRUNCH = "crunch";// скручивания
    String BICYCLE_CRUNCH_SITTING = "bicycleCrunchSitting";// велосипед
    String GLUTE_BRIDGE = "gluteBridge";// ягодичный мостик
    String MOUNTAIN_CLIMBER = "mountainClimber";// подьем в гору
    String SKATERS = "skaters";//перепрыгивания вбок с ноги на ногу с заведением одной за вторую
    String WALKING_LUNGES = "walkingLunges";//выпады
    String DONKEY_KICK = "donkeyKick";// стоя на четвереньках подьем ноги вверх
    String BANDED_LATERAL_WALK = "bandedLateralWalk";// шаги в сторону в резинкой
    String BULGARIAN_SPLIT_SQUAT = "bulgarianSplitSquat";//подседания с одной ногой сзади на ящике
    String DUCK_WALKS = "duckWalks";//из полуприседа по одной ноге на колени и обратно
    String BACK_SQUAT = "backSquat";//присед со штангой
    String FRONT_SQUAT = "frontSquat";//присед со штангой спереди
    String HACK_SQUAT = "hackSquat";//жим ногами в тренажере стоя
    String MACHINE_HAMSTRING_CURL = "machineHamstringCurl";//сгибание бицепса бедра в тренажере
    String MACHINE_LEG_EXTENSION = "machineLegExtension";//разгибание ног в тренажере
    String BOX_JUMPS = "boxJumps";//запрыгивания на коробку
    String STANDING_BARBELL_CALF_RAISE = "standingBarbellCalfRaise";//подьем на носки со штангой
    String SEAL_JUMPS = "sealJumps";//прыжки на носках ноги в стороны-вместе
    String JUMP_ROPE = "jumpRope";//скакалка
    String FARMER_S_WALK = "farmersWalk";// фермерская прогулка
    String BIKE = "bike";//велосипед
    String RUN = "run";//бег
}
